--------------------------------------------------------
--  File created - Saturday-December-07-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEETING_ROOM_ENTITY
--------------------------------------------------------

  CREATE TABLE "AWS"."MEETING_ROOM_ENTITY" 
   (	"ID" NUMBER(10,0), 
	"CAPACITY" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"FLOOR" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR)
   ) 
  TABLESPACE "USERS" ;
REM INSERTING into AWS.MEETING_ROOM_ENTITY
SET DEFINE OFF;
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (1052,10,'Google Play','15','New York ');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (1053,10,'Google Play','16','New York  ');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (2,0,'Room 0','8','Location 0');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (3,2,'Room 1','9','Location 1');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (4,4,'Room 2','10','Location 2');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (5,5,'some name','10','string');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (6,8,'Room 4','12','Location 4');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (7,10,'Room 5','13','Location 5');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (8,12,'Room 6','1','Location 6');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (9,14,'Room 7','2','Location 7');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (10,16,'Room 8','3','Location 8');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (11,18,'Room 9','4','Location 9');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (12,20,'Room 10','5','Location 10');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (13,22,'Room 11','6','Location 11');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (14,24,'Room 12','7','Location 12');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (15,26,'Room 13','8','Location 13');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (16,28,'Room 14','9','Location 14');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (17,30,'Room 15','10','Location 15');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (18,32,'Room 16','11','Location 16');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (19,34,'Room 17','12','Location 17');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (20,36,'Room 18','13','Location 18');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (21,38,'Room 19','1','Location 19');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (22,40,'Room 20','2','Location 20');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (23,42,'Room 21','3','Location 21');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (24,44,'Room 22','4','Location 22');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (25,46,'Room 23','5','Location 23');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (26,48,'Room 24','6','Location 24');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (27,50,'Room 25','7','Location 25');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (28,52,'Room 26','8','Location 26');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (29,54,'Room 27','9','Location 27');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (30,56,'Room 28','10','Location 28');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (31,58,'Room 29','11','Location 29');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (32,60,'Room 30','12','Location 30');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (33,62,'Room 31','13','Location 31');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (34,64,'Room 32','1','Location 32');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (35,66,'Room 33','2','Location 33');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (36,68,'Room 34','3','Location 34');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (37,70,'Room 35','4','Location 35');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (38,72,'Room 36','5','Location 36');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (39,74,'Room 37','6','Location 37');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (40,76,'Room 38','7','Location 38');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (41,78,'Room 39','8','Location 39');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (42,80,'Room 40','9','Location 40');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (43,82,'Room 41','10','Location 41');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (44,84,'Room 42','11','Location 42');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (45,86,'Room 43','12','Location 43');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (46,88,'Room 44','13','Location 44');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (47,90,'Room 45','1','Location 45');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (48,92,'Room 46','2','Location 46');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (49,94,'Room 47','3','Location 47');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (50,96,'Room 48','4','Location 48');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (51,98,'Room 49','5','Location 49');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (52,100,'Room 50','6','Location 50');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (53,102,'Room 51','7','Location 51');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (54,104,'Room 52','8','Location 52');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (55,106,'Room 53','9','Location 53');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (56,108,'Room 54','10','Location 54');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (57,110,'Room 55','11','Location 55');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (58,112,'Room 56','12','Location 56');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (59,114,'Room 57','13','Location 57');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (60,116,'Room 58','1','Location 58');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (61,118,'Room 59','2','Location 59');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (62,120,'Room 60','3','Location 60');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (63,122,'Room 61','4','Location 61');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (64,124,'Room 62','5','Location 62');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (65,126,'Room 63','6','Location 63');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (66,128,'Room 64','7','Location 64');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (67,130,'Room 65','8','Location 65');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (68,132,'Room 66','9','Location 66');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (69,134,'Room 67','10','Location 67');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (70,136,'Room 68','11','Location 68');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (71,138,'Room 69','12','Location 69');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (72,140,'Room 70','13','Location 70');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (73,142,'Room 71','1','Location 71');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (74,144,'Room 72','2','Location 72');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (75,146,'Room 73','3','Location 73');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (76,148,'Room 74','4','Location 74');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (77,150,'Room 75','5','Location 75');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (78,152,'Room 76','6','Location 76');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (79,154,'Room 77','7','Location 77');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (80,156,'Room 78','8','Location 78');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (81,158,'Room 79','9','Location 79');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (82,160,'Room 80','10','Location 80');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (83,162,'Room 81','11','Location 81');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (84,164,'Room 82','12','Location 82');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (85,166,'Room 83','13','Location 83');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (86,168,'Room 84','1','Location 84');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (87,170,'Room 85','2','Location 85');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (88,172,'Room 86','3','Location 86');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (89,174,'Room 87','4','Location 87');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (90,176,'Room 88','5','Location 88');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (91,178,'Room 89','6','Location 89');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (92,180,'Room 90','7','Location 90');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (93,182,'Room 91','8','Location 91');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (94,184,'Room 92','9','Location 92');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (95,186,'Room 93','10','Location 93');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (96,188,'Room 94','11','Location 94');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (97,190,'Room 95','12','Location 95');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (98,192,'Room 96','13','Location 96');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (99,194,'Room 97','1','Location 97');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (100,196,'Room 98','2','Location 98');
Insert into AWS.MEETING_ROOM_ENTITY (ID,CAPACITY,DESCRIPTION,FLOOR,LOCATION) values (101,198,'Room 99','3','Location 99');
--------------------------------------------------------
--  DDL for Index SYS_C009131
--------------------------------------------------------

  CREATE UNIQUE INDEX "AWS"."SYS_C009131" ON "AWS"."MEETING_ROOM_ENTITY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEETING_ROOM_ENTITY
--------------------------------------------------------

  ALTER TABLE "AWS"."MEETING_ROOM_ENTITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AWS"."MEETING_ROOM_ENTITY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
